name: build
# based on https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

on:
  schedule: 
    - cron: "15 3 * * *"

jobs:
  build:
    runs-on: linux
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          install: true # set default builder
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: build and push images
        run: |
          docker build --push --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 --tag aktur/openvpn .
          echo 'All done :-)'
