name: sync with forked repo

on:
  schedule:
    - cron: "30 7 * * 1,4"
    # scheduled at 07:30 every Monday and Thursday

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Pull upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.0
        with:
          upstream_repository: kylemanna/docker-openvpn.git
          upstream_branch: master
          git_pull_args: --ff-only

      - name: Check for new commits
        if: steps.sync.outputs.has-new-commits
        run: echo "There were new commits."

      - name: Timestamp
        run: date
